version: "3.0"
services:
  react:
    build:
      context: ./ytdl-front
    ports:
      - "10500:5173"
    volumes:
     - ./ytdl-front/src:/app/src
  express:
    build:
      context: ./ytdl-backend
    ports:
      - "10501:3000"
    volumes:
     - ./:/code 
    environment:
      - REDIS_URL=redis
      - NODE_ENV=development
  redis:
    image: redis/redis-stack
    ports:
      - "8001:8001"
  worker:
    build:
      context: ./ytdl-worker
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - WORKER_ENV=PROD
      - S3_BUCKET