version: "3.0"
services:
  react:
    build:
      context: ./ytdl-front
    ports:
      - "10500:3000"
    volumes:
     - ./ytdl-front/src:/app/src
  express:
    build:
      context: ./ytdl-backend
    ports:
      - "10501:3000"
    volumes:
     - ./:/code 
     - mp3-data:/mp3-data:ro
    environment:
      - REDIS_URL=redis
  redis:
    image: redis:alpine
  worker:
    build:
      context: ./ytdl-worker
    volumes:
      - mp3-data:/mp3-data
      
volumes:
    mp3-data: